# UI Swagger (page web)
nelmio_api_doc_ui:
    path: /api/docs
    controller: nelmio_api_doc.controller.swagger_ui

# Spécification OpenAPI en JSON
nelmio_api_doc_json:
    path: /api/docs.json
    controller: nelmio_api_doc.controller.swagger
